version: "3.9"

services:
  ps:
    container_name: ps
    build: .
    volumes:
      - ./cache:/app/cache
    networks:
      - my-network
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
