version: "3.9"

services:
  ps:
    container_name: ps
    build: .
    networks:
      - my-network
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-volume:/data/db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
