telegram:
  api_token: 1258815235:AAHabDcwDpSULOoCF7Kc-WYh-rlTxlKGYfo
  chat_id: -1001552306035
db:
  init_sql: "./assets/init.sql"
  alter_sql: "./assets/alter.sql"
  type: "sqlite3"
  path: "./cache/scan_results.db"